---
title: "Paramter estimation with death data"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
```{r, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```
```{r packages, echo = F, include=FALSE}
c_light <- c("#fee0d2")
c_mid <- c("#fc9272")
c_dark <- c("#de2d26")
c_simu <- "chartreuse3"
c_posterior = "orange"
c_prior = "aquamarine2"
library(formatR)
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE)
library(tidyverse)
library(readr)
library(readxl)
library(ggplot2)
library(lubridate)
library(rstan)
library(gridExtra)
library(parallel)
library(deSolve)
library(dplyr)
library(rstanarm)
library(tidybayes)
library(latex2exp)
library(writexl)
library(bayesplot)
library(hexbin)
library(mhsmm)
```
# Import Data

```{r import data, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
load("SEIRD_york_paper_results_actual.RData")
covid_data_york <- read_excel("Data/covid_data_leeds_york.xlsx", 
    sheet = "utla_2023-02-23_york", col_types = c("skip", 
        "skip", "date", "numeric", "numeric", 
        "numeric", "numeric"))
covid_data_york <- subset(covid_data_york,date>= "2020-03-17" & date <= "2020-07-1")

Deaths_cum_york <- covid_data_york$`Cumulative Deaths`
Deaths_york <- covid_data_york$`New Deaths`
Inf_cum_york <- covid_data_york$`Cumlative Cases`
Infected_york <- covid_data_york$`New Cases`

ggplot() +
    geom_point(data = covid_data_york, aes(date, Deaths_cum_york),colour = 'plum2', size = 2)
```
# Compile Model

```{r compile model}
rstan_options (auto_write = TRUE)
options (mc.cores = parallel::detectCores ())
cl <- parallel::makeCluster(3, setup_strategy = "sequential")

set.seed(3) # for reproductibility

N <- 211116 #total uk population

# times
n_days <- length(Deaths_cum_york)
t <- seq(1, n_days, by = 1)
t0 = 0
t <- t

#initial conditions
i0 <- Infected_york[1] #no of cases on 17/03
e0 <- 1
s0 <- N - i0 - e0
r0 <- 0
d0 <- Deaths_cum_york[1] # no of total deaths on 17/03

y0 = c(S = s0,E = e0, I = i0, R = r0, D=d0)
date_switch <- "2020-03-23"# date of introduction of control measures
tswitch <- covid_data_york %>% filter(date < date_switch) %>% nrow() + 1
# data for Stan
data_sir <- list(n_days = n_days, y0 = y0, t0 = t0, ts = t, N = N, newdeaths = Deaths_cum_york,tswitch=tswitch)


model <- stan_model("seirddeaths_switch.stan")
```

# Run the Sampling 

## Test sampling to diagnose any problems

```{r test model leeds, eval=FALSE, include=TRUE}

test_york <- sampling(model,
                data = data_sir,
                seed = 3,
                iter = 1000,
                chains = 1,
                cores = 1,
                control = list(max_treedepth = 15))
```

## Sampling for Full Iterations and Chains

```{r full model leeds, eval=FALSE, include=TRUE}
seird_phase1_preported_york <- sampling(model,
                data = data_sir,
                seed = 3,
                iter = 3000,
                chains = 4,
                cores = 4,
                control = list(max_treedepth = 15))
```
```{r stanfit leeds output}
color_scheme_set("purple")
#show the parameter estimates along with the posterior density plots and the MCMC chains to obsever how well the chains have mixed. 
pars=c('beta','sigma','nu','delta', "R0", "recovery_time","phi",'latent_period','eta','mu','xi')
print(seird_york_paper_results$seird_phase1_preported_york, pars = pars, digits = 4)

plot(stan_dens(seird_york_paper_results$seird_phase1_preported_york, pars = c('beta','sigma','nu','delta', "phi"), separate_chains = TRUE))

plot(seird_york_paper_results$seird_phase1_preported_york, plotfun = "trace", pars = pars, inc_warmup = FALSE)
np <- nuts_params(seird_york_paper_results$seird_phase1_preported_york)

suppressWarnings(mcmc_pairs(seird_york_paper_results$seird_phase1_preported_york, pars = c('beta', 'delta', 'sigma', 'nu'), off_diag_args = list(size = 1, alpha = 0.5), diag_fun = "dens", off_diag_fun = "hex", condition = pairs_condition(nuts = "accept_stat__"),
  np = np,np_style = pairs_style_np(
  div_color = "green",
  div_shape = 4,
  div_size = 1)))

mcmc_intervals(seird_york_paper_results$seird_phase1_preported_york, pars = c('beta', 'delta', 'sigma', 'nu'))

#york_params <- as.data.frame(get_posterior_mean(seird_york_paper_results$seird_phase1_preported_york,pars)[,5])
#write_xlsx(york_params, "seird_york_paper.xlsx", col_names = FALSE)

## For test sampling 
#pars=c('beta','sigma','gamma','nu', "R0","p_reported", "recovery_time","phi",'latent_period','eta','mu','xi')
#print(test_york, pars = pars, digits = 5)
#plot(stan_dens(test, pars = c('beta','sigma', 'gamma','nu',"phi"), separate_chains = TRUE))
#plot(test, plotfun = "trace", pars = pars, inc_warmup = FALSE)

```
## Posterior Predictive Check

```{r post pred check leeds}
#posterior predictive check, how well did our model estimate the data curve.
 post_pred <- cbind(as.data.frame(summary(seird_york_paper_results$seird_phase1_preported_york, pars = "pred_newdeaths", probs = c(0.025, 0.05, 0.1, 0.5, 0.9, 0.95, 0.975))$summary), t, Deaths_cum_york)
post_pred
colnames(post_pred) <- make.names(colnames(post_pred))
date <- as.Date(covid_data_york$date, format = "%d-%m-%Y")
lockdown <- date[5]
ggplot(post_pred, mapping = aes(x = date)) +
 geom_ribbon(aes(ymin = X2.5., ymax = X97.5., colour = "grey"), fill = "grey", alpha = 0.6) + 
 geom_line(mapping = aes(x = date, y = X50., colour = "black")) +
geom_point(mapping = aes(x = date, y = Deaths_cum_york, colour = "red"), size = 0.5) +
   geom_vline(aes(xintercept = lockdown), color = 'blue', linetype = 2)+
   geom_text(aes(x = lockdown-2, y = 75, label="Lockdown Initiated UK"), angle = 90, size=5, color = 'blue')+
  labs(x = "Date", y = "Total Deaths") +
  scale_color_identity(name = "",
breaks = c("black", "red", "grey"),
labels = c("Median Fit", "Data Points"," 95% CI"),
guide = "legend")+
  theme(legend.position = "bottom")
```
## Evolution of $R_0$ Value

```{r reff leeds}
seird_york_paper_results$seird_phase1_preported_york %>% 
  spread_draws(Reff[n_days]) %>% 
  group_by(n_days) %>% 
  summarise(R0_mean = mean(Reff), R09 = quantile(Reff, 0.95), R01 = quantile(Reff, 0.05)) %>% 
   ggplot() +
   geom_ribbon(aes(x = t, ymin = R01, ymax = R09, color = 'grey'), fill = 'grey', alpha=0.5)+
  geom_line(mapping = aes(x = t, y = R0_mean, colour = "black")) +
   geom_vline(aes(xintercept = tswitch), color = 'blue' ,linetype = 2)+
  geom_text(aes(x = tswitch-2, y = 3.8, label="Lockdown Initiated UK"), angle = 90, size=5, color = 'blue')+
    labs(x = "Days Since 17/03/20", y =TeX(r'(Mean $R_0$ Value)'))+
  scale_color_identity(name = "",
breaks = c("black", "grey"),
labels = c("Mean Value"," 95% CI"),
guide = "legend")+
  theme(legend.position = "bottom")
```
## Evolution of $\beta(t)$

```{r beta eff leeds}
seird_york_paper_results$seird_phase1_preported_york %>% 
  spread_draws(beta_switch[n_days]) %>% 
  group_by(n_days) %>% 
  summarise(beta_mean = mean(beta_switch), beta9 = quantile(beta_switch, 0.95), beta1 = quantile(beta_switch, 0.05)) %>% 
   ggplot() +
   geom_ribbon(aes(x = t, ymin = beta1, ymax = beta9, color = 'grey'), fill = 'grey', alpha=0.5)+
  geom_line(mapping = aes(t, beta_mean, color = 'black')) +
     geom_vline(aes(xintercept = tswitch), color = 'blue' ,linetype = 2)+
  geom_text(aes(x = tswitch-2, y = 0.35, label="Lockdown Initiated UK"), angle = 90, size=5, color = 'blue')+
labs(x = "Days Since 17/03/20", y =TeX(r'(Mean $\beta(t)$ Value)'))+
  scale_color_identity(name = "",
breaks = c("black", "grey"),
labels = c("Mean Value"," 95% CI"),
guide = "legend")+
  theme(legend.position = "bottom")
```
